import type { Question } from '../game-state'

export const matematicaQuestions: Question[] = [
  // FACIL (50)
  { id:'m1',category:'Matematica',text:'Quanto e 7 x 8?',options:['54','56','58','62'],correctIndex:1,difficulty:'easy' },
  { id:'m2',category:'Matematica',text:'Raiz quadrada de 144?',options:['10','11','12','14'],correctIndex:2,difficulty:'easy' },
  { id:'m3',category:'Matematica',text:'15% de 200?',options:['25','30','35','40'],correctIndex:1,difficulty:'easy' },
  { id:'m4',category:'Matematica',text:'Quantos lados tem um hexagono?',options:['5','6','7','8'],correctIndex:1,difficulty:'easy' },
  { id:'m5',category:'Matematica',text:'Quanto e 9 x 9?',options:['72','81','88','91'],correctIndex:1,difficulty:'easy' },
  { id:'m6',category:'Matematica',text:'Raiz quadrada de 64?',options:['6','7','8','9'],correctIndex:2,difficulty:'easy' },
  { id:'m7',category:'Matematica',text:'Quanto e 12 + 19?',options:['29','30','31','32'],correctIndex:2,difficulty:'easy' },
  { id:'m8',category:'Matematica',text:'Quanto e 100 - 37?',options:['57','63','67','73'],correctIndex:1,difficulty:'easy' },
  { id:'m9',category:'Matematica',text:'Metade de 250?',options:['115','120','125','130'],correctIndex:2,difficulty:'easy' },
  { id:'m10',category:'Matematica',text:'Dobro de 85?',options:['160','165','170','175'],correctIndex:2,difficulty:'easy' },
  { id:'m11',category:'Matematica',text:'Quanto e 6 x 7?',options:['36','40','42','48'],correctIndex:2,difficulty:'easy' },
  { id:'m12',category:'Matematica',text:'Quanto e 11 x 11?',options:['111','121','131','141'],correctIndex:1,difficulty:'easy' },
  { id:'m13',category:'Matematica',text:'Raiz quadrada de 49?',options:['5','6','7','8'],correctIndex:2,difficulty:'easy' },
  { id:'m14',category:'Matematica',text:'Quanto e 1000 / 8?',options:['120','125','130','150'],correctIndex:1,difficulty:'easy' },
  { id:'m15',category:'Matematica',text:'Quanto e 3 x 15?',options:['35','40','45','50'],correctIndex:2,difficulty:'easy' },
  { id:'m16',category:'Matematica',text:'Quanto e 200 + 350?',options:['500','525','550','575'],correctIndex:2,difficulty:'easy' },
  { id:'m17',category:'Matematica',text:'Quanto e 1/2 + 1/4?',options:['2/6','3/6','3/4','1/1'],correctIndex:2,difficulty:'easy' },
  { id:'m18',category:'Matematica',text:'Angulos de um triangulo somam?',options:['90','120','180','360'],correctIndex:2,difficulty:'easy' },
  { id:'m19',category:'Matematica',text:'Quanto e 5!?',options:['60','100','120','150'],correctIndex:2,difficulty:'easy' },
  { id:'m20',category:'Matematica',text:'Quantos cm em 1 metro?',options:['10','50','100','1000'],correctIndex:2,difficulty:'easy' },
  { id:'m21',category:'Matematica',text:'Quanto e 25 x 4?',options:['75','90','100','125'],correctIndex:2,difficulty:'easy' },
  { id:'m22',category:'Matematica',text:'Quanto e 2 + 2 x 3?',options:['6','8','10','12'],correctIndex:1,difficulty:'easy' },
  { id:'m23',category:'Matematica',text:'Raiz quadrada de 169?',options:['11','12','13','14'],correctIndex:2,difficulty:'easy' },
  { id:'m24',category:'Matematica',text:'Quanto e 0,5 + 0,75?',options:['1,0','1,15','1,25','1,5'],correctIndex:2,difficulty:'easy' },
  { id:'m25',category:'Matematica',text:'Quantos graus tem um angulo raso?',options:['90','120','180','360'],correctIndex:2,difficulty:'easy' },
  { id:'m26',category:'Matematica',text:'Quanto e 14 x 5?',options:['60','65','70','75'],correctIndex:2,difficulty:'easy' },
  { id:'m27',category:'Matematica',text:'Quanto e 1000 - 456?',options:['534','544','554','564'],correctIndex:1,difficulty:'easy' },
  { id:'m28',category:'Matematica',text:'Quanto e 8 x 12?',options:['84','88','92','96'],correctIndex:3,difficulty:'easy' },
  { id:'m29',category:'Matematica',text:'Qual e 10% de 350?',options:['30','35','40','45'],correctIndex:1,difficulty:'easy' },
  { id:'m30',category:'Matematica',text:'Quanto e 16 x 3?',options:['42','44','46','48'],correctIndex:3,difficulty:'easy' },
  { id:'m31',category:'Matematica',text:'Quanto e 72 / 9?',options:['6','7','8','9'],correctIndex:2,difficulty:'easy' },
  { id:'m32',category:'Matematica',text:'Quanto e 4 ao cubo?',options:['16','32','64','128'],correctIndex:2,difficulty:'easy' },
  { id:'m33',category:'Matematica',text:'Quanto e 0,1 x 0,1?',options:['0,01','0,1','0,2','1'],correctIndex:0,difficulty:'easy' },
  { id:'m34',category:'Matematica',text:'Quanto e 99 + 99?',options:['188','196','198','200'],correctIndex:2,difficulty:'easy' },
  { id:'m35',category:'Matematica',text:'Quanto e 500 / 25?',options:['15','20','25','30'],correctIndex:1,difficulty:'easy' },
  { id:'m36',category:'Matematica',text:'Quanto e 13 x 7?',options:['84','87','91','93'],correctIndex:2,difficulty:'easy' },
  { id:'m37',category:'Matematica',text:'Raiz quadrada de 196?',options:['12','13','14','15'],correctIndex:2,difficulty:'easy' },
  { id:'m38',category:'Matematica',text:'Quanto e 2/3 de 90?',options:['50','55','60','65'],correctIndex:2,difficulty:'easy' },
  { id:'m39',category:'Matematica',text:'Quanto e 1,5 x 4?',options:['4,5','5','5,5','6'],correctIndex:3,difficulty:'easy' },
  { id:'m40',category:'Matematica',text:'Quanto e 45 + 67?',options:['102','108','112','122'],correctIndex:2,difficulty:'easy' },
  { id:'m41',category:'Matematica',text:'Quanto e 17 x 6?',options:['96','98','102','108'],correctIndex:2,difficulty:'easy' },
  { id:'m42',category:'Matematica',text:'Quanto e 360 / 4?',options:['80','85','90','95'],correctIndex:2,difficulty:'easy' },
  { id:'m43',category:'Matematica',text:'Quanto e 2,5 x 2,5?',options:['5','5,25','6,25','6,5'],correctIndex:2,difficulty:'easy' },
  { id:'m44',category:'Matematica',text:'Quanto e 15 ao quadrado?',options:['125','200','225','250'],correctIndex:2,difficulty:'easy' },
  { id:'m45',category:'Matematica',text:'Quanto e 1/5 em decimal?',options:['0,1','0,15','0,2','0,25'],correctIndex:2,difficulty:'easy' },
  { id:'m46',category:'Matematica',text:'Quanto e 8 + 6 x 2?',options:['20','28','14','22'],correctIndex:0,difficulty:'easy' },
  { id:'m47',category:'Matematica',text:'Quanto e 144 / 12?',options:['10','11','12','13'],correctIndex:2,difficulty:'easy' },
  { id:'m48',category:'Matematica',text:'Quanto e 3/4 em porcentagem?',options:['60%','70%','75%','80%'],correctIndex:2,difficulty:'easy' },
  { id:'m49',category:'Matematica',text:'Quanto e a raiz cubica de 8?',options:['2','3','4','6'],correctIndex:0,difficulty:'easy' },
  { id:'m50',category:'Matematica',text:'Quanto e 19 x 5?',options:['85','90','95','100'],correctIndex:2,difficulty:'easy' },
  // MEDIO (100)
  { id:'m51',category:'Matematica',text:'Qual e o valor de log base 2 de 64?',options:['4','5','6','8'],correctIndex:2,difficulty:'medium' },
  { id:'m52',category:'Matematica',text:'Quanto e 2^8?',options:['128','256','512','1024'],correctIndex:1,difficulty:'medium' },
  { id:'m53',category:'Matematica',text:'MMC de 12 e 18?',options:['24','36','48','72'],correctIndex:1,difficulty:'medium' },
  { id:'m54',category:'Matematica',text:'MDC de 48 e 36?',options:['6','8','12','18'],correctIndex:2,difficulty:'medium' },
  { id:'m55',category:'Matematica',text:'Quanto e 17^2?',options:['272','279','289','291'],correctIndex:2,difficulty:'medium' },
  { id:'m56',category:'Matematica',text:'Qual fracao equivale a 0,375?',options:['1/3','3/8','2/5','3/7'],correctIndex:1,difficulty:'medium' },
  { id:'m57',category:'Matematica',text:'Se x+5=12, quanto e x?',options:['5','6','7','8'],correctIndex:2,difficulty:'medium' },
  { id:'m58',category:'Matematica',text:'Area de um triangulo com base 10 e altura 6?',options:['20','25','30','60'],correctIndex:2,difficulty:'medium' },
  { id:'m59',category:'Matematica',text:'Quanto e 3^5?',options:['81','162','243','729'],correctIndex:2,difficulty:'medium' },
  { id:'m60',category:'Matematica',text:'Soma dos 10 primeiros naturais?',options:['45','50','55','60'],correctIndex:2,difficulty:'medium' },
  { id:'m61',category:'Matematica',text:'Perimetro de um circulo com raio 7 (use pi=3,14)?',options:['21,98','43,96','49,00','153,86'],correctIndex:1,difficulty:'medium' },
  { id:'m62',category:'Matematica',text:'Quanto e 50 / 0,5?',options:['10','25','50','100'],correctIndex:3,difficulty:'medium' },
  { id:'m63',category:'Matematica',text:'Se 3x = 45, quanto e x?',options:['12','13','15','18'],correctIndex:2,difficulty:'medium' },
  { id:'m64',category:'Matematica',text:'Volume de um cubo de aresta 3?',options:['9','18','27','36'],correctIndex:2,difficulty:'medium' },
  { id:'m65',category:'Matematica',text:'Quanto e 7! / 5!?',options:['21','42','56','84'],correctIndex:1,difficulty:'medium' },
  { id:'m66',category:'Matematica',text:'Area de um quadrado com diagonal 10?',options:['25','50','75','100'],correctIndex:1,difficulty:'medium' },
  { id:'m67',category:'Matematica',text:'Quanto e 0,125 em fracao?',options:['1/6','1/7','1/8','1/9'],correctIndex:2,difficulty:'medium' },
  { id:'m68',category:'Matematica',text:'Soma dos angulos internos de um pentagono?',options:['360','450','540','720'],correctIndex:2,difficulty:'medium' },
  { id:'m69',category:'Matematica',text:'Quanto e raiz de 2 (aprox)?',options:['1,21','1,32','1,41','1,52'],correctIndex:2,difficulty:'medium' },
  { id:'m70',category:'Matematica',text:'Se 2^x = 32, x vale?',options:['3','4','5','6'],correctIndex:2,difficulty:'medium' },
  { id:'m71',category:'Matematica',text:'Quantos divisores tem o numero 36?',options:['6','7','8','9'],correctIndex:3,difficulty:'medium' },
  { id:'m72',category:'Matematica',text:'Quanto e C(5,2)?',options:['5','8','10','20'],correctIndex:2,difficulty:'medium' },
  { id:'m73',category:'Matematica',text:'Media aritmetica de 3, 7, 8, 12, 20?',options:['8','10','12','14'],correctIndex:1,difficulty:'medium' },
  { id:'m74',category:'Matematica',text:'Se f(x)=2x+3, f(4)=?',options:['8','10','11','13'],correctIndex:2,difficulty:'medium' },
  { id:'m75',category:'Matematica',text:'Quantas diagonais tem um hexagono?',options:['6','8','9','12'],correctIndex:2,difficulty:'medium' },
  { id:'m76',category:'Matematica',text:'Quanto e 0,6 periodica em fracao?',options:['2/3','3/5','6/10','1/6'],correctIndex:0,difficulty:'medium' },
  { id:'m77',category:'Matematica',text:'Quanto e sen(30)?',options:['0','0,5','0,707','1'],correctIndex:1,difficulty:'medium' },
  { id:'m78',category:'Matematica',text:'Quanto e cos(60)?',options:['0','0,5','0,707','1'],correctIndex:1,difficulty:'medium' },
  { id:'m79',category:'Matematica',text:'Area do trapezio com bases 5 e 9, altura 4?',options:['14','20','28','36'],correctIndex:2,difficulty:'medium' },
  { id:'m80',category:'Matematica',text:'Numero aureo (phi) vale aprox?',options:['1,414','1,500','1,618','1,732'],correctIndex:2,difficulty:'medium' },
  { id:'m81',category:'Matematica',text:'Probabilidade de tirar par em um dado?',options:['1/6','1/3','1/2','2/3'],correctIndex:2,difficulty:'medium' },
  { id:'m82',category:'Matematica',text:'Quantos subconjuntos tem um conjunto de 4 elementos?',options:['8','12','16','32'],correctIndex:2,difficulty:'medium' },
  { id:'m83',category:'Matematica',text:'Quanto e 4! x 2?',options:['24','36','48','96'],correctIndex:2,difficulty:'medium' },
  { id:'m84',category:'Matematica',text:'Se x^2=81, x positivo vale?',options:['7','8','9','10'],correctIndex:2,difficulty:'medium' },
  { id:'m85',category:'Matematica',text:'Hipotenusa de catetos 3 e 4?',options:['4','5','6','7'],correctIndex:1,difficulty:'medium' },
  { id:'m86',category:'Matematica',text:'Quanto e 22/7 (aprox)?',options:['2,71','3,00','3,14','3,33'],correctIndex:2,difficulty:'medium' },
  { id:'m87',category:'Matematica',text:'PA: a1=3, r=5. Qual e a10?',options:['43','48','50','53'],correctIndex:1,difficulty:'medium' },
  { id:'m88',category:'Matematica',text:'PG: a1=2, q=3. Qual e a4?',options:['18','27','54','162'],correctIndex:2,difficulty:'medium' },
  { id:'m89',category:'Matematica',text:'Quanto e 10^0?',options:['0','1','10','100'],correctIndex:1,difficulty:'medium' },
  { id:'m90',category:'Matematica',text:'Complemento de um angulo de 35 graus?',options:['45','55','65','145'],correctIndex:1,difficulty:'medium' },
  { id:'m91',category:'Matematica',text:'Quanto e log(1000)?',options:['1','2','3','4'],correctIndex:2,difficulty:'medium' },
  { id:'m92',category:'Matematica',text:'Se 5x-3=22, x vale?',options:['3','4','5','6'],correctIndex:2,difficulty:'medium' },
  { id:'m93',category:'Matematica',text:'Quantos vertices tem um cubo?',options:['4','6','8','12'],correctIndex:2,difficulty:'medium' },
  { id:'m94',category:'Matematica',text:'Area lateral de um cilindro: r=3, h=5?',options:['30pi','45pi','90pi','15pi'],correctIndex:0,difficulty:'medium' },
  { id:'m95',category:'Matematica',text:'Quanto e i^2 (unidade imaginaria)?',options:['1','0','-1','i'],correctIndex:2,difficulty:'medium' },
  { id:'m96',category:'Matematica',text:'Quanto e a soma 1+2+3+...+20?',options:['190','200','210','220'],correctIndex:2,difficulty:'medium' },
  { id:'m97',category:'Matematica',text:'Qual e o 7o termo da sequencia Fibonacci?',options:['8','11','13','21'],correctIndex:2,difficulty:'medium' },
  { id:'m98',category:'Matematica',text:'Se y=x^2, qual e y quando x=-3?',options:['-9','-6','6','9'],correctIndex:3,difficulty:'medium' },
  { id:'m99',category:'Matematica',text:'Quanto e 2^(-3)?',options:['1/6','1/8','1/4','-8'],correctIndex:1,difficulty:'medium' },
  { id:'m100',category:'Matematica',text:'Modulo de -15?',options:['-15','0','15','225'],correctIndex:2,difficulty:'medium' },
  { id:'m101',category:'Matematica',text:'Quanto e tg(45)?',options:['0','0,5','1','2'],correctIndex:2,difficulty:'medium' },
  { id:'m102',category:'Matematica',text:'Diagonal de um quadrado de lado 5?',options:['5raiz2','5raiz3','10','7,5'],correctIndex:0,difficulty:'medium' },
  { id:'m103',category:'Matematica',text:'Se A={1,2,3} e B={3,4,5}, A intersecao B?',options:['{1,2}','{3}','{3,4}','{1,5}'],correctIndex:1,difficulty:'medium' },
  { id:'m104',category:'Matematica',text:'Quantos numeros primos entre 1 e 20?',options:['6','7','8','9'],correctIndex:2,difficulty:'medium' },
  { id:'m105',category:'Matematica',text:'Raiz cubica de 125?',options:['3','4','5','6'],correctIndex:2,difficulty:'medium' },
  { id:'m106',category:'Matematica',text:'Quanto e A(5,3)?',options:['10','20','60','120'],correctIndex:2,difficulty:'medium' },
  { id:'m107',category:'Matematica',text:'Se x/4 + 2 = 5, x vale?',options:['8','10','12','16'],correctIndex:2,difficulty:'medium' },
  { id:'m108',category:'Matematica',text:'Quanto e 3,5 x 2,4?',options:['7,2','7,8','8,4','9,0'],correctIndex:2,difficulty:'medium' },
  { id:'m109',category:'Matematica',text:'Suplemento de 110 graus?',options:['50','60','70','80'],correctIndex:2,difficulty:'medium' },
  { id:'m110',category:'Matematica',text:'Quantas arestas tem um cubo?',options:['6','8','10','12'],correctIndex:3,difficulty:'medium' },
  { id:'m111',category:'Matematica',text:'Raiz quarta de 81?',options:['2','3','4','9'],correctIndex:1,difficulty:'medium' },
  { id:'m112',category:'Matematica',text:'Se f(x)=x^2-4, raizes sao?',options:['-2 e 2','-4 e 4','0 e 4','1 e 3'],correctIndex:0,difficulty:'medium' },
  { id:'m113',category:'Matematica',text:'Quanto e 0,999... (periodica)?',options:['0,999','0,99','1','Nao existe'],correctIndex:2,difficulty:'medium' },
  { id:'m114',category:'Matematica',text:'Volume de esfera r=3? (4/3 pi r^3)',options:['36pi','113,1','108pi','27pi'],correctIndex:0,difficulty:'medium' },
  { id:'m115',category:'Matematica',text:'Quanto e C(6,3)?',options:['10','15','20','30'],correctIndex:2,difficulty:'medium' },
  { id:'m116',category:'Matematica',text:'Se 2x+3y=12 e x=3, y vale?',options:['1','2','3','4'],correctIndex:1,difficulty:'medium' },
  { id:'m117',category:'Matematica',text:'Area de circulo com raio 5?',options:['10pi','15pi','25pi','50pi'],correctIndex:2,difficulty:'medium' },
  { id:'m118',category:'Matematica',text:'Quanto e 13^2?',options:['156','163','169','176'],correctIndex:2,difficulty:'medium' },
  { id:'m119',category:'Matematica',text:'Derivada de x^3?',options:['x^2','2x^2','3x^2','3x^3'],correctIndex:2,difficulty:'medium' },
  { id:'m120',category:'Matematica',text:'Integral de 2x dx?',options:['x^2+C','2x^2+C','x^2/2+C','4x+C'],correctIndex:0,difficulty:'medium' },
  { id:'m121',category:'Matematica',text:'Quanto e 5^0 + 3^0?',options:['0','1','2','8'],correctIndex:2,difficulty:'medium' },
  { id:'m122',category:'Matematica',text:'Se a=5 e b=12, hipotenusa=?',options:['11','12','13','14'],correctIndex:2,difficulty:'medium' },
  { id:'m123',category:'Matematica',text:'Numero de Euler (e) vale aprox?',options:['2,414','2,618','2,718','2,816'],correctIndex:2,difficulty:'medium' },
  { id:'m124',category:'Matematica',text:'Quanto e 20% de 450?',options:['80','85','90','95'],correctIndex:2,difficulty:'medium' },
  { id:'m125',category:'Matematica',text:'Quantas faces tem um icosaedro?',options:['10','12','16','20'],correctIndex:3,difficulty:'medium' },
  { id:'m126',category:'Matematica',text:'Se x^2+x-6=0, raizes sao?',options:['-3 e 2','-2 e 3','1 e 6','-1 e 6'],correctIndex:0,difficulty:'medium' },
  { id:'m127',category:'Matematica',text:'Mediana de 3,5,7,9,11?',options:['5','7','8','9'],correctIndex:1,difficulty:'medium' },
  { id:'m128',category:'Matematica',text:'Quanto e 2^10?',options:['512','1000','1024','2048'],correctIndex:2,difficulty:'medium' },
  { id:'m129',category:'Matematica',text:'PA: a1=2, an=50, r=4. Quantos termos?',options:['11','12','13','14'],correctIndex:2,difficulty:'medium' },
  { id:'m130',category:'Matematica',text:'Area de losango: d1=6, d2=8?',options:['14','20','24','48'],correctIndex:2,difficulty:'medium' },
  { id:'m131',category:'Matematica',text:'Quanto e |3-7|?',options:['-4','4','10','1'],correctIndex:1,difficulty:'medium' },
  { id:'m132',category:'Matematica',text:'Variancia de {2,4,6}: media=4',options:['2','2,67','4','8'],correctIndex:1,difficulty:'medium' },
  { id:'m133',category:'Matematica',text:'Quanto e 125^(1/3)?',options:['3','4','5','25'],correctIndex:2,difficulty:'medium' },
  { id:'m134',category:'Matematica',text:'Se f(x)=3x-1, f(f(2))=?',options:['11','14','15','17'],correctIndex:1,difficulty:'medium' },
  { id:'m135',category:'Matematica',text:'Quanto e ln(e)?',options:['0','1','e','2,71'],correctIndex:1,difficulty:'medium' },
  { id:'m136',category:'Matematica',text:'Distancia entre (0,0) e (3,4)?',options:['3','4','5','7'],correctIndex:2,difficulty:'medium' },
  { id:'m137',category:'Matematica',text:'Quanto e o determinante de [[1,2],[3,4]]?',options:['-2','-1','1','2'],correctIndex:0,difficulty:'medium' },
  { id:'m138',category:'Matematica',text:'Quantas faces tem um dodecaedro?',options:['10','12','14','20'],correctIndex:1,difficulty:'medium' },
  { id:'m139',category:'Matematica',text:'Se sen(x)=1, x vale?',options:['0','45','90','180'],correctIndex:2,difficulty:'medium' },
  { id:'m140',category:'Matematica',text:'Quanto e 6C2 x 2?',options:['20','24','30','36'],correctIndex:2,difficulty:'medium' },
  { id:'m141',category:'Matematica',text:'Se a+b=10, ab=21, a^2+b^2=?',options:['42','52','58','79'],correctIndex:2,difficulty:'medium' },
  { id:'m142',category:'Matematica',text:'Soma dos angulos de um hexagono?',options:['540','600','660','720'],correctIndex:3,difficulty:'medium' },
  { id:'m143',category:'Matematica',text:'Quanto e 4^(3/2)?',options:['4','6','8','12'],correctIndex:2,difficulty:'medium' },
  { id:'m144',category:'Matematica',text:'Se log2(x)=5, x=?',options:['10','16','25','32'],correctIndex:3,difficulty:'medium' },
  { id:'m145',category:'Matematica',text:'Quantas diagonais tem um octogono?',options:['16','18','20','24'],correctIndex:2,difficulty:'medium' },
  { id:'m146',category:'Matematica',text:'Quanto e C(8,2)?',options:['16','24','28','56'],correctIndex:2,difficulty:'medium' },
  { id:'m147',category:'Matematica',text:'Area do setor circular: r=6, angulo=60?',options:['3pi','6pi','12pi','36pi'],correctIndex:1,difficulty:'medium' },
  { id:'m148',category:'Matematica',text:'Se 3^x=81, x vale?',options:['2','3','4','5'],correctIndex:2,difficulty:'medium' },
  { id:'m149',category:'Matematica',text:'Raiz quadrada de 0,25?',options:['0,05','0,25','0,5','5'],correctIndex:2,difficulty:'medium' },
  { id:'m150',category:'Matematica',text:'Quanto e a soma de uma PG infinita: a1=4, q=1/2?',options:['4','6','8','16'],correctIndex:2,difficulty:'medium' },
  // DIFICIL (250)
  { id:'m151',category:'Matematica',text:'Qual e a derivada de ln(x^2+1)?',options:['2x/(x^2+1)','1/(x^2+1)','2x*ln(x)','x^2+1'],correctIndex:0,difficulty:'hard' },
  { id:'m152',category:'Matematica',text:'Integral definida de 0 a 1 de x^2 dx?',options:['1/4','1/3','1/2','1'],correctIndex:1,difficulty:'hard' },
  { id:'m153',category:'Matematica',text:'Quantos numeros primos existem entre 100 e 110?',options:['0','1','2','3'],correctIndex:1,difficulty:'hard' },
  { id:'m154',category:'Matematica',text:'Se z=3+4i, |z|=?',options:['3','4','5','7'],correctIndex:2,difficulty:'hard' },
  { id:'m155',category:'Matematica',text:'Qual e o 20o termo de Fibonacci?',options:['4181','5702','6765','8320'],correctIndex:2,difficulty:'hard' },
  { id:'m156',category:'Matematica',text:'Limite de (sen x)/x quando x->0?',options:['0','1','infinito','nao existe'],correctIndex:1,difficulty:'hard' },
  { id:'m157',category:'Matematica',text:'Quantos anagramas tem BANANA?',options:['30','60','120','720'],correctIndex:1,difficulty:'hard' },
  { id:'m158',category:'Matematica',text:'Se A e 3x3 e det(A)=5, det(2A)=?',options:['10','20','40','80'],correctIndex:2,difficulty:'hard' },
  { id:'m159',category:'Matematica',text:'Qual e o resto de 2^100 dividido por 3?',options:['0','1','2','Nao existe'],correctIndex:1,difficulty:'hard' },
  { id:'m160',category:'Matematica',text:'Serie 1+1/2+1/4+1/8+... converge para?',options:['1','1,5','2','infinito'],correctIndex:2,difficulty:'hard' },
  { id:'m161',category:'Matematica',text:'Se f(x)=e^(2x), f\'\'(0)=?',options:['1','2','4','e^2'],correctIndex:2,difficulty:'hard' },
  { id:'m162',category:'Matematica',text:'Quantos numeros de 3 digitos sao divisiveis por 7?',options:['112','128','129','130'],correctIndex:2,difficulty:'hard' },
  { id:'m163',category:'Matematica',text:'Traco da matriz identidade 4x4?',options:['1','2','3','4'],correctIndex:3,difficulty:'hard' },
  { id:'m164',category:'Matematica',text:'Se sen(x)=3/5, cos(x)=? (1o quadrante)',options:['2/5','3/5','4/5','5/3'],correctIndex:2,difficulty:'hard' },
  { id:'m165',category:'Matematica',text:'Quanto e C(10,5)?',options:['120','210','252','504'],correctIndex:2,difficulty:'hard' },
  { id:'m166',category:'Matematica',text:'Derivada de x^x?',options:['x^x','x^(x-1)','x^x(ln x+1)','x*x^(x-1)'],correctIndex:2,difficulty:'hard' },
  { id:'m167',category:'Matematica',text:'Se p(x)=x^3-6x^2+11x-6, raiz que nao e 1 ou 2?',options:['0','3','4','6'],correctIndex:1,difficulty:'hard' },
  { id:'m168',category:'Matematica',text:'Volume do tetraedro regular de aresta 2?',options:['8raiz2/12','8raiz2/3','4raiz2/3','2raiz2/3'],correctIndex:2,difficulty:'hard' },
  { id:'m169',category:'Matematica',text:'Quanto e Euler Totient phi(12)?',options:['2','3','4','6'],correctIndex:2,difficulty:'hard' },
  { id:'m170',category:'Matematica',text:'Se A e B sao independentes, P(A)=0,3, P(B)=0,5, P(AuB)=?',options:['0,55','0,60','0,65','0,80'],correctIndex:2,difficulty:'hard' },
  { id:'m171',category:'Matematica',text:'Qual e a soma da serie 1/1! + 1/2! + 1/3! + ...?',options:['1','e-1','e','2'],correctIndex:1,difficulty:'hard' },
  { id:'m172',category:'Matematica',text:'Numero de particoes do inteiro 7?',options:['11','13','15','17'],correctIndex:2,difficulty:'hard' },
  { id:'m173',category:'Matematica',text:'Se det(A)=3 e det(B)=4, det(AB)=?',options:['7','12','1','3/4'],correctIndex:1,difficulty:'hard' },
  { id:'m174',category:'Matematica',text:'Qual e o raio do circulo inscrito no triangulo de lados 3,4,5?',options:['0,5','1','1,5','2'],correctIndex:1,difficulty:'hard' },
  { id:'m175',category:'Matematica',text:'Quanto e arctan(1) em radianos?',options:['pi/6','pi/4','pi/3','pi/2'],correctIndex:1,difficulty:'hard' },
  { id:'m176',category:'Matematica',text:'Se x=2 e raiz dupla de x^3-6x^2+12x-8, o polinomio e?',options:['(x-2)^3','(x-2)^2(x+2)','(x-1)(x-2)^2','(x-2)(x^2-4)'],correctIndex:0,difficulty:'hard' },
  { id:'m177',category:'Matematica',text:'Laplaciano de f(x,y)=x^2+y^2?',options:['2','4','2x+2y','x+y'],correctIndex:1,difficulty:'hard' },
  { id:'m178',category:'Matematica',text:'Quantas permutacoes de ABCDE comecam com A?',options:['12','24','48','120'],correctIndex:1,difficulty:'hard' },
  { id:'m179',category:'Matematica',text:'Se a media de 5 numeros e 8 e tiramos o 4, nova media?',options:['8','9','10','11'],correctIndex:1,difficulty:'hard' },
  { id:'m180',category:'Matematica',text:'Quanto e a integral de 1/(x^2+1) dx?',options:['ln(x^2+1)','arctan(x)+C','1/x+C','arcsen(x)+C'],correctIndex:1,difficulty:'hard' },
  { id:'m181',category:'Matematica',text:'Numero de grafos simples com 4 vertices?',options:['6','8','11','16'],correctIndex:2,difficulty:'hard' },
  { id:'m182',category:'Matematica',text:'Se f(x)=x^3, f\'\'\'(x)=?',options:['0','3','6','6x'],correctIndex:2,difficulty:'hard' },
  { id:'m183',category:'Matematica',text:'Congruencia: 17 mod 5 =?',options:['1','2','3','4'],correctIndex:1,difficulty:'hard' },
  { id:'m184',category:'Matematica',text:'Qual e o numero cromatico do grafo completo K4?',options:['2','3','4','5'],correctIndex:2,difficulty:'hard' },
  { id:'m185',category:'Matematica',text:'Se A={1,...,10}, quantos subconjuntos de 3 elem?',options:['45','84','120','210'],correctIndex:2,difficulty:'hard' },
  { id:'m186',category:'Matematica',text:'Quanto e a serie geometrica 3+3/2+3/4+...?',options:['4','5','6','9'],correctIndex:2,difficulty:'hard' },
  { id:'m187',category:'Matematica',text:'Se f e g bijecoes, f*g e?',options:['Injecao','Sobrejecao','Bijecao','Nenhuma'],correctIndex:2,difficulty:'hard' },
  { id:'m188',category:'Matematica',text:'Quantos zeros tem 100!?',options:['12','18','24','30'],correctIndex:2,difficulty:'hard' },
  { id:'m189',category:'Matematica',text:'Qual e o autovalor de [[2,0],[0,3]] que nao e 2?',options:['0','1','3','5'],correctIndex:2,difficulty:'hard' },
  { id:'m190',category:'Matematica',text:'Divergencia do campo F=(x,y,z)?',options:['0','1','3','xyz'],correctIndex:2,difficulty:'hard' },
  { id:'m191',category:'Matematica',text:'Quantos primos gemeos existem entre 1 e 50?',options:['4','5','6','8'],correctIndex:2,difficulty:'hard' },
  { id:'m192',category:'Matematica',text:'Determinante de [[1,2,3],[4,5,6],[7,8,9]]?',options:['-3','0','3','6'],correctIndex:1,difficulty:'hard' },
  { id:'m193',category:'Matematica',text:'Se sen(2x)=2sen(x)cos(x), cos(2x)=?',options:['2cos^2(x)-1','cos^2(x)-1','1-sin^2(x)','2cos(x)'],correctIndex:0,difficulty:'hard' },
  { id:'m194',category:'Matematica',text:'Quanto e a funcao Gamma de 5, G(5)?',options:['5','24','120','720'],correctIndex:1,difficulty:'hard' },
  { id:'m195',category:'Matematica',text:'Se x^2+y^2=25, dy/dx em (3,4)?',options:['-3/4','-4/3','3/4','4/3'],correctIndex:0,difficulty:'hard' },
  { id:'m196',category:'Matematica',text:'Qual e o grau do polinomio minimo de raiz2+raiz3 sobre Q?',options:['2','3','4','6'],correctIndex:2,difficulty:'hard' },
  { id:'m197',category:'Matematica',text:'Quantos automorfismos tem Z/6Z?',options:['1','2','3','6'],correctIndex:1,difficulty:'hard' },
  { id:'m198',category:'Matematica',text:'Qual grupo tem ordem 4 e nao e ciclico?',options:['Z4','V4 (Klein)','S3','D3'],correctIndex:1,difficulty:'hard' },
  { id:'m199',category:'Matematica',text:'Quanto e a soma 1^2+2^2+...+10^2?',options:['285','355','385','420'],correctIndex:2,difficulty:'hard' },
  { id:'m200',category:'Matematica',text:'Se lim(n->inf) (1+1/n)^n = ?',options:['1','2','e','infinito'],correctIndex:2,difficulty:'hard' },
  { id:'m201',category:'Matematica',text:'Posto da matriz [[1,2],[2,4]]?',options:['0','1','2','3'],correctIndex:1,difficulty:'hard' },
  { id:'m202',category:'Matematica',text:'Transformada de Laplace de e^(at)?',options:['1/(s-a)','s/(s-a)','1/(s+a)','a/(s^2)'],correctIndex:0,difficulty:'hard' },
  { id:'m203',category:'Matematica',text:'Se f(x)=sen(x), serie de Taylor ate x^3 em x=0?',options:['x-x^2/2','x-x^3/6','x+x^3/3','x-x^3/3'],correctIndex:1,difficulty:'hard' },
  { id:'m204',category:'Matematica',text:'Quantos caminhos de (0,0) a (4,3) so subindo/direita?',options:['12','20','35','70'],correctIndex:2,difficulty:'hard' },
  { id:'m205',category:'Matematica',text:'Se X~N(50,10^2), P(X>50)=?',options:['0,25','0,50','0,68','0,95'],correctIndex:1,difficulty:'hard' },
  { id:'m206',category:'Matematica',text:'Raio de convergencia de sum x^n/n! ?',options:['0','1','e','infinito'],correctIndex:3,difficulty:'hard' },
  { id:'m207',category:'Matematica',text:'Se dim(V)=5 e dim(W)=3 subesp, dim(V+W) max?',options:['3','5','7','8'],correctIndex:3,difficulty:'hard' },
  { id:'m208',category:'Matematica',text:'Produto vetorial de (1,0,0) e (0,1,0)?',options:['(0,0,0)','(0,0,1)','(1,1,0)','(0,0,-1)'],correctIndex:1,difficulty:'hard' },
  { id:'m209',category:'Matematica',text:'Se f(x)=|x|, f\'(0)=?',options:['0','1','-1','Nao existe'],correctIndex:3,difficulty:'hard' },
  { id:'m210',category:'Matematica',text:'Quantos grupos abelianos de ordem 8 existem (a menos de iso)?',options:['1','2','3','5'],correctIndex:2,difficulty:'hard' },
  { id:'m211',category:'Matematica',text:'Se T:R^3->R^2 linear, dim(Ker T) minimo?',options:['0','1','2','3'],correctIndex:1,difficulty:'hard' },
  { id:'m212',category:'Matematica',text:'Numero de Catalan C3=?',options:['2','4','5','14'],correctIndex:2,difficulty:'hard' },
  { id:'m213',category:'Matematica',text:'Se p e primo > 2, p mod 2 =?',options:['0','1','p-1','Depende'],correctIndex:1,difficulty:'hard' },
  { id:'m214',category:'Matematica',text:'Qual e o numero de Ramsey R(3,3)?',options:['4','5','6','9'],correctIndex:2,difficulty:'hard' },
  { id:'m215',category:'Matematica',text:'Se 2^p - 1 e primo, como se chama?',options:['Fermat','Mersenne','Sophie Germain','Wilson'],correctIndex:1,difficulty:'hard' },
  { id:'m216',category:'Matematica',text:'Quanto e zeta(2) = 1+1/4+1/9+...?',options:['1','pi^2/6','e','ln(2)'],correctIndex:1,difficulty:'hard' },
  { id:'m217',category:'Matematica',text:'Curl do campo F=(y,-x,0)?',options:['(0,0,0)','(0,0,-2)','(0,0,2)','(1,1,0)'],correctIndex:1,difficulty:'hard' },
  { id:'m218',category:'Matematica',text:'Ordem do grupo simetrico S4?',options:['12','16','24','48'],correctIndex:2,difficulty:'hard' },
  { id:'m219',category:'Matematica',text:'Se f analitica e f(z)=0 para todo z real, entao f=?',options:['0','constante','real','Nao se sabe'],correctIndex:0,difficulty:'hard' },
  { id:'m220',category:'Matematica',text:'Dimensao do espaco de matrizes simetricas 3x3?',options:['3','5','6','9'],correctIndex:2,difficulty:'hard' },
  { id:'m221',category:'Matematica',text:'Se chi(G)=k, G contem K_k como subgrafo?',options:['Sempre','Nunca','Nem sempre','So se planar'],correctIndex:2,difficulty:'hard' },
  { id:'m222',category:'Matematica',text:'Menor n tal que n! > 10^6?',options:['8','9','10','11'],correctIndex:2,difficulty:'hard' },
  { id:'m223',category:'Matematica',text:'Quanto e phi(100)? (totiente de Euler)',options:['20','32','40','50'],correctIndex:2,difficulty:'hard' },
  { id:'m224',category:'Matematica',text:'Se A e B comutam, e^(A+B) = ?',options:['e^A + e^B','e^A * e^B','e^A - e^B','Nao simplifica'],correctIndex:1,difficulty:'hard' },
  { id:'m225',category:'Matematica',text:'Numero de arvores rotuladas com 4 vertices (Cayley)?',options:['4','8','12','16'],correctIndex:3,difficulty:'hard' },
  { id:'m226',category:'Matematica',text:'Se integral de 0 a inf de e^(-x^2) dx = ?',options:['1','raiz(pi)','raiz(pi)/2','pi'],correctIndex:2,difficulty:'hard' },
  { id:'m227',category:'Matematica',text:'Grau minimo de vertice em grafo planar simples?',options:['Ate 3','Ate 4','Ate 5','Ate 6'],correctIndex:2,difficulty:'hard' },
  { id:'m228',category:'Matematica',text:'Se f e continua em [a,b], integral f existe? (Riemann)',options:['Sempre','Nunca','Depende','So se derivavel'],correctIndex:0,difficulty:'hard' },
  { id:'m229',category:'Matematica',text:'Cardinalidade de R (reais)?',options:['aleph_0','aleph_1','c (continuo)','2^aleph_0'],correctIndex:3,difficulty:'hard' },
  { id:'m230',category:'Matematica',text:'Se p|ab e p primo, entao?',options:['p|a ou p|b','p|a e p|b','p|a+b','p=ab'],correctIndex:0,difficulty:'hard' },
  { id:'m231',category:'Matematica',text:'Classe de complexidade de SAT?',options:['P','NP-completo','coNP','PSPACE'],correctIndex:1,difficulty:'hard' },
  { id:'m232',category:'Matematica',text:'Se A e nilpotente, todos autovalores sao?',options:['1','-1','0','Reais'],correctIndex:2,difficulty:'hard' },
  { id:'m233',category:'Matematica',text:'Quantos corpos finitos de ordem 9 existem?',options:['0','1','2','infinitos'],correctIndex:1,difficulty:'hard' },
  { id:'m234',category:'Matematica',text:'O teorema de Bolzano-Weierstrass garante?',options:['Convergencia','Subsequencia convergente','Limitacao','Continuidade'],correctIndex:1,difficulty:'hard' },
  { id:'m235',category:'Matematica',text:'Se G tem 7 vertices e 22 arestas, e planar?',options:['Sim','Nao','Depende','So se bipartido'],correctIndex:1,difficulty:'hard' },
  { id:'m236',category:'Matematica',text:'Qual e o genus do toro?',options:['0','1','2','3'],correctIndex:1,difficulty:'hard' },
  { id:'m237',category:'Matematica',text:'Se f:R->R crescente e limitada, lim(x->inf) existe?',options:['Sempre','Nunca','So se continua','So se derivavel'],correctIndex:0,difficulty:'hard' },
  { id:'m238',category:'Matematica',text:'Quanto e o discriminante de x^2-5x+6?',options:['1','5','13','25'],correctIndex:0,difficulty:'hard' },
  { id:'m239',category:'Matematica',text:'Se dim(V)=n, dim(V*)=?',options:['n','n-1','2n','n^2'],correctIndex:0,difficulty:'hard' },
  { id:'m240',category:'Matematica',text:'Qual funcao gera os numeros de Bell?',options:['e^(e^x-1)','e^x','x*e^x','ln(1+e^x)'],correctIndex:0,difficulty:'hard' },
  { id:'m241',category:'Matematica',text:'Numero de Stirling S(4,2)=?',options:['3','5','7','11'],correctIndex:2,difficulty:'hard' },
  { id:'m242',category:'Matematica',text:'Se X~Poisson(3), P(X=0)=?',options:['e^(-3)','3e^(-3)','1/3','0'],correctIndex:0,difficulty:'hard' },
  { id:'m243',category:'Matematica',text:'Todo grupo de ordem prima e?',options:['Abeliano','Ciclico','Simples','Todos acima'],correctIndex:3,difficulty:'hard' },
  { id:'m244',category:'Matematica',text:'Se f holomofa e |f|=const, f e?',options:['Constante','Linear','Polinomial','Nao existe'],correctIndex:0,difficulty:'hard' },
  { id:'m245',category:'Matematica',text:'Quantos numeros perfeitos pares sao conhecidos (2024)?',options:['4','12','31','51'],correctIndex:3,difficulty:'hard' },
  { id:'m246',category:'Matematica',text:'Se R e PID, todo ideal e?',options:['Maximal','Primo','Principal','Nilpotente'],correctIndex:2,difficulty:'hard' },
  { id:'m247',category:'Matematica',text:'Formula de Euler para poliedros: V-A+F=?',options:['0','1','2','3'],correctIndex:2,difficulty:'hard' },
  { id:'m248',category:'Matematica',text:'Se lim(a_n)=L e lim(b_n)=M, lim(a_n*b_n)=?',options:['L+M','L*M','L/M','LM+1'],correctIndex:1,difficulty:'hard' },
  { id:'m249',category:'Matematica',text:'Espaco dual de l^1 e?',options:['l^1','l^2','l^inf','c_0'],correctIndex:2,difficulty:'hard' },
  { id:'m250',category:'Matematica',text:'Numero de derangements de {1,2,3,4}?',options:['6','9','12','24'],correctIndex:1,difficulty:'hard' },
  { id:'m251',category:'Matematica',text:'Se f(z) tem polo de ordem 2 em z=0, Res(f,0) e?',options:['lim z*f(z)','lim d/dz[z^2*f(z)]','lim z^2*f(z)','f\'(0)'],correctIndex:1,difficulty:'hard' },
  { id:'m252',category:'Matematica',text:'Dimensao do espaco de polinomios de grau <=n?',options:['n','n+1','2n','n^2'],correctIndex:1,difficulty:'hard' },
  { id:'m253',category:'Matematica',text:'Constante de Kaprekar: 6174. Quantos digitos?',options:['3','4','5','6'],correctIndex:1,difficulty:'hard' },
  { id:'m254',category:'Matematica',text:'Se G e conexo com n vertices, minimo de arestas?',options:['n/2','n-1','n','n+1'],correctIndex:1,difficulty:'hard' },
  { id:'m255',category:'Matematica',text:'Teorema de Sylow: se p^k | |G|, existe subgrupo de ordem?',options:['p','p^k','|G|/p','p^(k+1)'],correctIndex:1,difficulty:'hard' },
  { id:'m256',category:'Matematica',text:'Integral de sec(x) dx?',options:['ln|sec+tan|+C','tan(x)+C','sec(x)tan(x)+C','arctan(sec x)+C'],correctIndex:0,difficulty:'hard' },
  { id:'m257',category:'Matematica',text:'Quantos primos sao menores que 100?',options:['20','23','25','29'],correctIndex:2,difficulty:'hard' },
  { id:'m258',category:'Matematica',text:'Se M e variedade 2D compacta orientavel genus g, chi(M)=?',options:['2g','2-2g','g-2','2g-2'],correctIndex:1,difficulty:'hard' },
  { id:'m259',category:'Matematica',text:'Qual e o menor numero abundante?',options:['6','10','12','18'],correctIndex:2,difficulty:'hard' },
  { id:'m260',category:'Matematica',text:'Se T:V->W e linear, dim(V)=dim(Im T)+?',options:['dim(W)','dim(Ker T)','dim(Coker T)','1'],correctIndex:1,difficulty:'hard' },
  { id:'m261',category:'Matematica',text:'Quanto e i^i (principal)?',options:['1','-1','e^(-pi/2)','pi'],correctIndex:2,difficulty:'hard' },
  { id:'m262',category:'Matematica',text:'Numero de coloracoes proprias de K3 com 3 cores?',options:['3','6','9','27'],correctIndex:1,difficulty:'hard' },
  { id:'m263',category:'Matematica',text:'Se X~Binomial(n=10,p=0,5), E[X]=?',options:['2,5','5','7,5','10'],correctIndex:1,difficulty:'hard' },
  { id:'m264',category:'Matematica',text:'Funcao zeta de Riemann: zeros triviais estao em?',options:['Inteiros pares negativos','Inteiros impares','s=1/2+it','s=0'],correctIndex:0,difficulty:'hard' },
  { id:'m265',category:'Matematica',text:'Se ||v||=3, ||w||=4, v.w=0, ||v+w||=?',options:['1','5','7','12'],correctIndex:1,difficulty:'hard' },
  { id:'m266',category:'Matematica',text:'Quantas particoes de 5 existem?',options:['5','6','7','8'],correctIndex:2,difficulty:'hard' },
  { id:'m267',category:'Matematica',text:'Raio espectral de [[0,1],[1,0]]?',options:['0','1','2','raiz 2'],correctIndex:1,difficulty:'hard' },
  { id:'m268',category:'Matematica',text:'Quanto e a constante de Euler-Mascheroni (aprox)?',options:['0,398','0,477','0,577','0,693'],correctIndex:2,difficulty:'hard' },
  { id:'m269',category:'Matematica',text:'Se f(x)=x*sen(1/x), lim(x->0)?',options:['0','1','-1','Nao existe'],correctIndex:0,difficulty:'hard' },
  { id:'m270',category:'Matematica',text:'Quantos quadrados perfeitos entre 1 e 1000?',options:['29','30','31','32'],correctIndex:2,difficulty:'hard' },
  { id:'m271',category:'Matematica',text:'Norma Frobenius da identidade 3x3?',options:['1','raiz3','3','9'],correctIndex:1,difficulty:'hard' },
  { id:'m272',category:'Matematica',text:'Se G finito e |G|=p^2, G e?',options:['Ciclico','Abeliano','Simples','Nao-abeliano'],correctIndex:1,difficulty:'hard' },
  { id:'m273',category:'Matematica',text:'Periodo da funcao tan(2x)?',options:['pi/4','pi/2','pi','2pi'],correctIndex:1,difficulty:'hard' },
  { id:'m274',category:'Matematica',text:'Quantos inteiros 1<=n<=100 sao coprimos com 100?',options:['20','30','40','50'],correctIndex:2,difficulty:'hard' },
  { id:'m275',category:'Matematica',text:'Se dy/dx = y, y(0)=1, y(1)=?',options:['1','2','e','e^2'],correctIndex:2,difficulty:'hard' },
  { id:'m276',category:'Matematica',text:'Qual e o radical de 12 (em teoria de aneis)?',options:['2','3','6','2*3'],correctIndex:2,difficulty:'hard' },
  { id:'m277',category:'Matematica',text:'Numero cromatico de grafo bipartido?',options:['1','2','3','Depende'],correctIndex:1,difficulty:'hard' },
  { id:'m278',category:'Matematica',text:'Se f e Lebesgue integravel, f e mensuravel?',options:['Sempre','Nunca','Depende','So se continua'],correctIndex:0,difficulty:'hard' },
  { id:'m279',category:'Matematica',text:'Quanto e B_4 (4o numero de Bell)?',options:['5','10','15','20'],correctIndex:2,difficulty:'hard' },
  { id:'m280',category:'Matematica',text:'Se A e hermitiana, autovalores sao?',options:['Complexos','Reais','Imaginarios','Unitarios'],correctIndex:1,difficulty:'hard' },
  { id:'m281',category:'Matematica',text:'Quantos divisores tem 360?',options:['18','20','24','30'],correctIndex:2,difficulty:'hard' },
  { id:'m282',category:'Matematica',text:'Se f:C->C inteira e limitada, f e? (Liouville)',options:['Zero','Constante','Polinomial','Nao existe'],correctIndex:1,difficulty:'hard' },
  { id:'m283',category:'Matematica',text:'Indice do subgrupo A_n em S_n?',options:['1','2','n','n!'],correctIndex:1,difficulty:'hard' },
  { id:'m284',category:'Matematica',text:'Se H e espaco de Hilbert, todo subespaco fechado tem complemento?',options:['Sim','Nao','So de dim finita','So separavel'],correctIndex:0,difficulty:'hard' },
  { id:'m285',category:'Matematica',text:'Que numero e triangular e quadrado perfeito?',options:['1 e 36','1, 36 e 1225','6 e 28','Nenhum alem de 1'],correctIndex:1,difficulty:'hard' },
  { id:'m286',category:'Matematica',text:'Grau do campo de decomposicao de x^4-2 sobre Q?',options:['4','6','8','12'],correctIndex:2,difficulty:'hard' },
  { id:'m287',category:'Matematica',text:'Se mu e medida de Lebesgue, mu(Q inter [0,1])=?',options:['0','1','1/2','infinito'],correctIndex:0,difficulty:'hard' },
  { id:'m288',category:'Matematica',text:'Pi_1(S^1) (grupo fundamental do circulo)?',options:['0','Z','Z/2Z','Livre em 2 ger'],correctIndex:1,difficulty:'hard' },
  { id:'m289',category:'Matematica',text:'Se X~Geometrica(p=1/3), E[X]=?',options:['1/3','2','3','9'],correctIndex:2,difficulty:'hard' },
  { id:'m290',category:'Matematica',text:'Quanto e o Jacobiano de (r*cos t, r*sin t)?',options:['1','r','r^2','2r'],correctIndex:1,difficulty:'hard' },
  { id:'m291',category:'Matematica',text:'Numero de Bernoulli B_1?',options:['-1/2','0','1/2','1'],correctIndex:0,difficulty:'hard' },
  { id:'m292',category:'Matematica',text:'Se T normal, autoespaco sao ortogonais entre si?',options:['Sempre','Nunca','So se hermitiano','Depende'],correctIndex:0,difficulty:'hard' },
  { id:'m293',category:'Matematica',text:'Classe de isomorfismo de Z/2Z x Z/2Z?',options:['Z/4Z','V4','Z/2Z','S3'],correctIndex:1,difficulty:'hard' },
  { id:'m294',category:'Matematica',text:'Soma de todos divisores de 28?',options:['28','48','56','64'],correctIndex:2,difficulty:'hard' },
  { id:'m295',category:'Matematica',text:'Se f continua em [0,1] e f(0)<0, f(1)>0, existe c com f(c)=0?',options:['Sempre (Bolzano)','Nem sempre','So se derivavel','So se monotona'],correctIndex:0,difficulty:'hard' },
  { id:'m296',category:'Matematica',text:'Quanto e a serie 1-1/3+1/5-1/7+...?',options:['1','pi/4','ln(2)','pi/6'],correctIndex:1,difficulty:'hard' },
  { id:'m297',category:'Matematica',text:'Dimensao cohomologica de S^2?',options:['1','2','3','infinita'],correctIndex:1,difficulty:'hard' },
  { id:'m298',category:'Matematica',text:'Se p(n) = particoes de n, p(10)=?',options:['22','30','42','56'],correctIndex:2,difficulty:'hard' },
  { id:'m299',category:'Matematica',text:'Menores alternados de [[a,b],[c,d]] sao?',options:['a, d, ad-bc','a, b, c, d','a+d, ad-bc','ad, bc'],correctIndex:0,difficulty:'hard' },
  { id:'m300',category:'Matematica',text:'Se M e anel comutativo local, quantos ideais maximais?',options:['0','1','2','Depende'],correctIndex:1,difficulty:'hard' },
  { id:'m301',category:'Matematica',text:'Quanto e sum_{k=0}^{n} C(n,k) ?',options:['n!','2^n','n^2','n*2^(n-1)'],correctIndex:1,difficulty:'hard' },
  { id:'m302',category:'Matematica',text:'Projecao ortogonal de (3,4) sobre (1,0)?',options:['(3,0)','(4,0)','(0,4)','(3,4)'],correctIndex:0,difficulty:'hard' },
  { id:'m303',category:'Matematica',text:'Qual e a complexidade de merge sort?',options:['O(n)','O(n log n)','O(n^2)','O(log n)'],correctIndex:1,difficulty:'hard' },
  { id:'m304',category:'Matematica',text:'Se det(A)=0, A e?',options:['Inversivel','Singular','Unitaria','Ortogonal'],correctIndex:1,difficulty:'hard' },
  { id:'m305',category:'Matematica',text:'Quantas inversoes tem a permutacao (3,1,2)?',options:['1','2','3','4'],correctIndex:1,difficulty:'hard' },
  { id:'m306',category:'Matematica',text:'Se G age transitivamente em X, |X| divide |G|?',options:['Sempre','Nunca','So se abeliano','Depende'],correctIndex:0,difficulty:'hard' },
  { id:'m307',category:'Matematica',text:'Quanto e 1+2+4+8+...+2^9?',options:['511','512','1023','1024'],correctIndex:2,difficulty:'hard' },
  { id:'m308',category:'Matematica',text:'Se f(x)=e^(-x^2), f tem maximo em?',options:['x=-1','x=0','x=1','Nao tem'],correctIndex:1,difficulty:'hard' },
  { id:'m309',category:'Matematica',text:'Menor grupo nao-abeliano?',options:['Z4','V4','S3','D4'],correctIndex:2,difficulty:'hard' },
  { id:'m310',category:'Matematica',text:'Se an = (-1)^n / n, a serie converge?',options:['Sim (Leibniz)','Nao','Diverge p/ +inf','Oscila'],correctIndex:0,difficulty:'hard' },
  { id:'m311',category:'Matematica',text:'Quanto e o comprimento do arco de y=x^2 de 0 a 1 (aprox)?',options:['1,15','1,28','1,48','1,73'],correctIndex:2,difficulty:'hard' },
  { id:'m312',category:'Matematica',text:'Tipo de isomorfismo de Z/12Z?',options:['Z/3Z x Z/4Z','Z/2Z x Z/6Z','Z/12Z','Todos acima'],correctIndex:3,difficulty:'hard' },
  { id:'m313',category:'Matematica',text:'Quanto e Tr(A^T * A) se A=[[1,2],[3,4]]?',options:['10','20','30','40'],correctIndex:2,difficulty:'hard' },
  { id:'m314',category:'Matematica',text:'Propriedade de Arq. dos reais: para todo x>0 existe n com?',options:['n>x','1/n<x','n^2>x','Todos acima'],correctIndex:0,difficulty:'hard' },
  { id:'m315',category:'Matematica',text:'Se f:R->R diferenciavel e f\'=f, entao f(x)=?',options:['Ce^x','Cx','C*sen(x)','Constante'],correctIndex:0,difficulty:'hard' },
  { id:'m316',category:'Matematica',text:'Quantos subgrupos tem Z/6Z?',options:['2','3','4','6'],correctIndex:2,difficulty:'hard' },
  { id:'m317',category:'Matematica',text:'Se rank(A)=r e A e mxn, nullity(A)=?',options:['m-r','n-r','r','mn-r'],correctIndex:1,difficulty:'hard' },
  { id:'m318',category:'Matematica',text:'Quanto e o permanente de [[1,1],[1,1]]?',options:['0','1','2','4'],correctIndex:2,difficulty:'hard' },
  { id:'m319',category:'Matematica',text:'Funcao de Mobius mu(6)=?',options:['-1','0','1','2'],correctIndex:2,difficulty:'hard' },
  { id:'m320',category:'Matematica',text:'Se X e Y indep, Var(X+Y)=?',options:['Var(X)+Var(Y)','Var(X)*Var(Y)','max(Var X,Var Y)','0'],correctIndex:0,difficulty:'hard' },
  { id:'m321',category:'Matematica',text:'Produto tensorial Z/2Z tens Z/3Z?',options:['Z/6Z','Z/2Z','Z/3Z','0'],correctIndex:3,difficulty:'hard' },
  { id:'m322',category:'Matematica',text:'Se p=4k+1 primo, p e soma de dois quadrados?',options:['Sempre (Fermat)','Nunca','Depende','So se k primo'],correctIndex:0,difficulty:'hard' },
  { id:'m323',category:'Matematica',text:'Quanto e a area sob e^(-x) de 0 a infinito?',options:['0','1','e','infinito'],correctIndex:1,difficulty:'hard' },
  { id:'m324',category:'Matematica',text:'Numero de Mersenne M_7 = 2^7-1 e primo?',options:['Sim','Nao, =128','Nao, divisivel por 3','Nao, divisivel por 127'],correctIndex:0,difficulty:'hard' },
  { id:'m325',category:'Matematica',text:'Se K e corpo com 4 elementos, char(K)=?',options:['0','2','3','4'],correctIndex:1,difficulty:'hard' },
  { id:'m326',category:'Matematica',text:'Pi_1(S^2) (grupo fund. esfera)?',options:['0 (trivial)','Z','Z/2Z','Z^2'],correctIndex:0,difficulty:'hard' },
  { id:'m327',category:'Matematica',text:'Se f(z)=1/z, residuo em z=0?',options:['0','1','-1','infinito'],correctIndex:1,difficulty:'hard' },
  { id:'m328',category:'Matematica',text:'Quanto e o numero de Carmichael 561 = ?',options:['3*11*17','3*7*23','3*11*19','7*11*13'],correctIndex:0,difficulty:'hard' },
  { id:'m329',category:'Matematica',text:'Se G e grafo com grau min >= k, contem caminho de comprimento?',options:['k-1','k','k+1','2k'],correctIndex:1,difficulty:'hard' },
  { id:'m330',category:'Matematica',text:'Quanto e C(2n,n) / (n+1) para n=3?',options:['4','5','14','42'],correctIndex:1,difficulty:'hard' },
  { id:'m331',category:'Matematica',text:'Se A ortogonal, det(A) e?',options:['0','1 ou -1','Qualquer real','Qualquer complexo'],correctIndex:1,difficulty:'hard' },
  { id:'m332',category:'Matematica',text:'Quanto e gcd(Fib(6), Fib(9))?',options:['1','2','Fib(3)=2','Fib(gcd(6,9))=Fib(3)=2'],correctIndex:3,difficulty:'hard' },
  { id:'m333',category:'Matematica',text:'Se V e W espacos vetoriais dim 3 e 4, dim(Hom(V,W))=?',options:['7','12','64','81'],correctIndex:1,difficulty:'hard' },
  { id:'m334',category:'Matematica',text:'Numero ciclotomico phi_6(x)=?',options:['x^2-x+1','x^2+x+1','x^2+1','x^2-1'],correctIndex:0,difficulty:'hard' },
  { id:'m335',category:'Matematica',text:'Se f Lipschitz continua, f e absolutamente continua?',options:['Sim','Nao','So em R','Depende'],correctIndex:0,difficulty:'hard' },
  { id:'m336',category:'Matematica',text:'Quanto e o determinante de Vandermonde 2x2: [[1,a],[1,b]]?',options:['a-b','b-a','ab','a+b'],correctIndex:1,difficulty:'hard' },
  { id:'m337',category:'Matematica',text:'Funcao geradora de Fibonacci?',options:['x/(1-x-x^2)','1/(1-x)^2','x/(1-x)','e^x-1'],correctIndex:0,difficulty:'hard' },
  { id:'m338',category:'Matematica',text:'Se M modulo finitamente gerado sobre PID, M e soma direta de?',options:['Ciclicos','Livres','Simples','Projetivos'],correctIndex:0,difficulty:'hard' },
  { id:'m339',category:'Matematica',text:'Cobertura universal de S^1?',options:['R','R^2','S^2','S^1'],correctIndex:0,difficulty:'hard' },
  { id:'m340',category:'Matematica',text:'Se p(x) irredutivel sobre Q grau 3, grupo de Galois pode ser?',options:['S3 ou Z3','S3 apenas','Z3 apenas','A3 ou S3'],correctIndex:0,difficulty:'hard' },
  { id:'m341',category:'Matematica',text:'Quanto e integral dupla de 1 sobre disco r<=1?',options:['1','pi','2pi','4pi'],correctIndex:1,difficulty:'hard' },
  { id:'m342',category:'Matematica',text:'Se an = n^(1/n), lim(n->inf) an?',options:['0','1','e','infinito'],correctIndex:1,difficulty:'hard' },
  { id:'m343',category:'Matematica',text:'Complexidade do melhor algoritmo de multiplicacao de matrizes (2024)?',options:['O(n^3)','O(n^2.807)','O(n^2.373)','O(n^2)'],correctIndex:2,difficulty:'hard' },
  { id:'m344',category:'Matematica',text:'Se X~Uniforme(0,1), E[X^2]=?',options:['1/4','1/3','1/2','1'],correctIndex:1,difficulty:'hard' },
  { id:'m345',category:'Matematica',text:'Quanto e o indice de Z em Q como grupos aditivos?',options:['2','Finito','Infinito','Nao definido'],correctIndex:2,difficulty:'hard' },
  { id:'m346',category:'Matematica',text:'Se G planar e bipartido com n vertices, max arestas?',options:['2n-4','3n-6','n^2/4','n-1'],correctIndex:0,difficulty:'hard' },
  { id:'m347',category:'Matematica',text:'Teorema de Cayley: |S_n| = ?',options:['n','n!','2^n','n^n'],correctIndex:1,difficulty:'hard' },
  { id:'m348',category:'Matematica',text:'Se f analitica e f(1/n)=0 para todo n, f=?',options:['0','Constante','Polinomial','Nao determinavel'],correctIndex:0,difficulty:'hard' },
  { id:'m349',category:'Matematica',text:'Numero de Fermat F_5 = 2^32+1 e primo?',options:['Sim','Nao (641 divide)','Nao comprovado','Depende'],correctIndex:1,difficulty:'hard' },
  { id:'m350',category:'Matematica',text:'Se T compacto em Hilbert, espectro e?',options:['Finito','Contavel com 0 acumulacao','Continuo','Vazio'],correctIndex:1,difficulty:'hard' },
  { id:'m351',category:'Matematica',text:'Quanto e Catalan(5)?',options:['14','42','132','429'],correctIndex:1,difficulty:'hard' },
  { id:'m352',category:'Matematica',text:'Se K extensao de F grau 2, K e?',options:['Normal','Separavel','Galois','Depende de char'],correctIndex:3,difficulty:'hard' },
  { id:'m353',category:'Matematica',text:'Menor primo irregular?',options:['37','59','67','101'],correctIndex:0,difficulty:'hard' },
  { id:'m354',category:'Matematica',text:'Se f:R^n->R^m linear, grafo de f e subespaco de dim?',options:['n','m','n+m','nm'],correctIndex:0,difficulty:'hard' },
  { id:'m355',category:'Matematica',text:'Numero de classes laterais de A_4 em S_4?',options:['1','2','3','4'],correctIndex:1,difficulty:'hard' },
  { id:'m356',category:'Matematica',text:'Se integral de |f|^2 < inf, f pertence a?',options:['L^1','L^2','L^inf','C^0'],correctIndex:1,difficulty:'hard' },
  { id:'m357',category:'Matematica',text:'Quanto e a funcao partição p(20)?',options:['385','627','792','1002'],correctIndex:1,difficulty:'hard' },
  { id:'m358',category:'Matematica',text:'Dual de L^p e L^q com 1/p+1/q=1. Se p=3, q=?',options:['1/3','3/2','2','3'],correctIndex:1,difficulty:'hard' },
  { id:'m359',category:'Matematica',text:'Quantos automorfismos tem o grupo Z?',options:['1','2','Infinitos','0'],correctIndex:1,difficulty:'hard' },
  { id:'m360',category:'Matematica',text:'Se H^1(S^1;Z)=?',options:['0','Z','Z/2Z','Z^2'],correctIndex:1,difficulty:'hard' },
  { id:'m361',category:'Matematica',text:'Conjectura de Goldbach: todo par > 2 e soma de?',options:['2 primos','3 primos','primo e quadrado','2 impares'],correctIndex:0,difficulty:'hard' },
  { id:'m362',category:'Matematica',text:'Se A e B sao semelhantes, tem mesmos?',options:['Autovalores','Autovetores','Forma','Nada em comum'],correctIndex:0,difficulty:'hard' },
  { id:'m363',category:'Matematica',text:'Teorema de Hahn-Banach garante extensao de?',options:['Funcionais lineares','Operadores','Isometrias','Projecoes'],correctIndex:0,difficulty:'hard' },
  { id:'m364',category:'Matematica',text:'Se G e 3-conexo planar, existe imersao unica?',options:['Sim (Whitney)','Nao','So se 4-conexo','Depende'],correctIndex:0,difficulty:'hard' },
  { id:'m365',category:'Matematica',text:'Teorema de Fermat-Euler: a^phi(n) mod n = ? se gcd(a,n)=1',options:['0','1','a','phi(n)'],correctIndex:1,difficulty:'hard' },
  { id:'m366',category:'Matematica',text:'Quanto e a soma dos reciprocos dos primos?',options:['pi^2/6','Finita','Diverge','ln(2)'],correctIndex:2,difficulty:'hard' },
  { id:'m367',category:'Matematica',text:'Se f:R->R continua e injetora, f e?',options:['Estritamente monotona','Sobrejetora','Derivavel','Bijetora'],correctIndex:0,difficulty:'hard' },
  { id:'m368',category:'Matematica',text:'Menor grupo simples nao-abeliano?',options:['Z5','A4','A5','S3'],correctIndex:2,difficulty:'hard' },
  { id:'m369',category:'Matematica',text:'Quanto e Gamma(1/2)?',options:['1','pi','raiz(pi)','raiz(2)'],correctIndex:2,difficulty:'hard' },
  { id:'m370',category:'Matematica',text:'Se R e dominio, S^(-1)R (localizacao) e dominio?',options:['Sempre','Nunca','So se R PID','Depende'],correctIndex:0,difficulty:'hard' },
  { id:'m371',category:'Matematica',text:'Quanto e tau(24) (func num divisores)?',options:['4','6','8','12'],correctIndex:2,difficulty:'hard' },
  { id:'m372',category:'Matematica',text:'Se X Hausdorff e compacto, X e?',options:['Normal','Metrizavel','Paracompacto','Todos acima'],correctIndex:0,difficulty:'hard' },
  { id:'m373',category:'Matematica',text:'Problema: P = NP?',options:['Provado P=NP','Provado P!=NP','Aberto','Indecidivel'],correctIndex:2,difficulty:'hard' },
  { id:'m374',category:'Matematica',text:'Ultimo teorema de Fermat: provado por?',options:['Euler','Gauss','Wiles','Perelman'],correctIndex:2,difficulty:'hard' },
  { id:'m375',category:'Matematica',text:'Hipotese de Riemann: status (2024)?',options:['Provada','Refutada','Aberta','Indecidivel'],correctIndex:2,difficulty:'hard' },
  { id:'m376',category:'Matematica',text:'Dimensao de Hausdorff do conjunto de Cantor?',options:['0','log2/log3','1/2','1'],correctIndex:1,difficulty:'hard' },
  { id:'m377',category:'Matematica',text:'Se K corpo finito |K|=q, |GL(2,K)|=?',options:['q^4','(q^2-1)(q^2-q)','q^4-q^2','q(q-1)^2'],correctIndex:1,difficulty:'hard' },
  { id:'m378',category:'Matematica',text:'Qual e o primeiro primo de Wilson (n com (n-1)!+1 div por n^2)?',options:['2','5','13','563'],correctIndex:1,difficulty:'hard' },
  { id:'m379',category:'Matematica',text:'Se M variedade 3D fechada orientavel, H_3(M;Z)=?',options:['0','Z','Z/2Z','Depende'],correctIndex:1,difficulty:'hard' },
  { id:'m380',category:'Matematica',text:'Teorema de Banach-Tarski: aplicavel em R^n para n>=?',options:['1','2','3','4'],correctIndex:2,difficulty:'hard' },
  { id:'m381',category:'Matematica',text:'Se f(x)=sum a_n x^n com raio R, f\'(x) tem raio?',options:['R','R/2','2R','Depende'],correctIndex:0,difficulty:'hard' },
  { id:'m382',category:'Matematica',text:'Grupo de Galois de x^4-2 sobre Q?',options:['Z4','V4','D4','S4'],correctIndex:2,difficulty:'hard' },
  { id:'m383',category:'Matematica',text:'Funcao W de Lambert: W(e)=?',options:['0','1','e','1/e'],correctIndex:1,difficulty:'hard' },
  { id:'m384',category:'Matematica',text:'Se espaco metrico completo e total limitado, e?',options:['Compacto','Conexo','Separavel','Localmente compacto'],correctIndex:0,difficulty:'hard' },
  { id:'m385',category:'Matematica',text:'Quanto e sigma(12) (soma de divisores)?',options:['16','24','28','36'],correctIndex:2,difficulty:'hard' },
  { id:'m386',category:'Matematica',text:'Invariante de Arf vive em?',options:['Z','Z/2Z','Z/4Z','Q'],correctIndex:1,difficulty:'hard' },
  { id:'m387',category:'Matematica',text:'Se X~Chi-quadrado(k), E[X]=?',options:['k/2','k','2k','k^2'],correctIndex:1,difficulty:'hard' },
  { id:'m388',category:'Matematica',text:'Numero de Wieferich < 10000?',options:['0','1','2','3'],correctIndex:2,difficulty:'hard' },
  { id:'m389',category:'Matematica',text:'Se G e grupo livre em 2 geradores, G contem?',options:['Subgrupo livre em n ger','So subgrupos finitos','So subgrupos ciclicos','Nenhum subgrupo normal'],correctIndex:0,difficulty:'hard' },
  { id:'m390',category:'Matematica',text:'Teorema de Brouwer: toda f continua de B^n em B^n tem?',options:['Ponto fixo','Ponto sela','Ponto critico','Ciclo limite'],correctIndex:0,difficulty:'hard' },
  { id:'m391',category:'Matematica',text:'Se omega = e^(2pi i/n), sum_{k=0}^{n-1} omega^k =?',options:['0','1','n','-1'],correctIndex:0,difficulty:'hard' },
  { id:'m392',category:'Matematica',text:'Conjectura de Collatz: provada?',options:['Sim','Nao','Refutada','Indecidivel'],correctIndex:1,difficulty:'hard' },
  { id:'m393',category:'Matematica',text:'Se espaco L^2 e?',options:['Banach mas nao Hilbert','Hilbert','Frechet','Nenhum'],correctIndex:1,difficulty:'hard' },
  { id:'m394',category:'Matematica',text:'Qual primo divide todos C(p,k) para 0<k<p?',options:['2','k','p','p-1'],correctIndex:2,difficulty:'hard' },
  { id:'m395',category:'Matematica',text:'Dimensao de SO(3)?',options:['1','2','3','6'],correctIndex:2,difficulty:'hard' },
  { id:'m396',category:'Matematica',text:'Se categoria tem todos limites finitos, e?',options:['Completa','Cocompleta','Abeliana','Topos'],correctIndex:0,difficulty:'hard' },
  { id:'m397',category:'Matematica',text:'Numero de Young tableaux standard de forma (3,2)?',options:['3','4','5','6'],correctIndex:2,difficulty:'hard' },
  { id:'m398',category:'Matematica',text:'Se Z[i] (inteiros Gaussianos), 5 fatora como?',options:['5','(2+i)(2-i)','(1+2i)(1-2i)','Irredutivel'],correctIndex:1,difficulty:'hard' },
  { id:'m399',category:'Matematica',text:'Propriedade de Baire: conjunto de Cantor e de 1a categoria?',options:['Sim','Nao (e magro)','Depende','Nenhum'],correctIndex:0,difficulty:'hard' },
  { id:'m400',category:'Matematica',text:'Conjectura dos primos gemeos: status (2024)?',options:['Provada','Refutada','Aberta','Provada para p>10^9'],correctIndex:2,difficulty:'hard' },
]
